name: protgps-streamlit
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch=2.0.0
  - pandas=2.0.3
  - numpy=1.23.4
  - matplotlib=3.7.1
  - tqdm=4.62.3
  - openpyxl=3.1.2
  - pip=24.0
  - pip:
    - streamlit==1.40.1
    - plotly==5.15.0
    - pytorch-lightning==1.9.5